# Generated by Django 3.2.11 on 2022-02-20 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image_ipfs_uri', models.CharField(max_length=46, null=True)),
                ('image_low_res_ipfs_uri', models.CharField(max_length=46, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NFTType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('representative_image_ipfs_uri', models.CharField(max_length=46, null=True)),
                ('representative_image_low_res_ipfs_uri', models.CharField(max_length=46, null=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfts.nft')),
            ],
        ),
    ]
