# Generated by Django 3.2.11 on 2022-02-21 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0002_alter_nft_nft_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='nft_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfttype', to='nfts.nfttype'),
        ),
    ]
