# Generated by Django 3.2.11 on 2022-02-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0003_alter_nft_nft_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='metadata_ipfs_uri',
            field=models.CharField(default='notavalidipfsuri', max_length=46),
            preserve_default=False,
        ),
    ]
