# Generated by Django 3.2.11 on 2022-02-23 16:46

from django.db import migrations
import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0004_nft_metadata_ipfs_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='mint_tx',
            field=gnosis.eth.django.models.Keccak256Field(null=True),
        ),
    ]
