# Generated by Django 3.2.11 on 2022-02-24 22:32

from django.db import migrations, models
import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0007_auto_20220224_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('spotify_refresh_token', models.CharField(max_length=200)),
                ('ethereum_address', gnosis.eth.django.models.EthereumAddressV2Field()),
            ],
        ),
    ]
