# Generated by Django 3.2.11 on 2022-02-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0008_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_access_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='spotify_refresh_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
