# Generated by Django 3.2.11 on 2022-02-25 21:06

from django.db import migrations, models
import django.db.models.deletion
import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0009_auto_20220225_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='NftClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', gnosis.eth.django.models.Keccak256Field(null=True)),
                ('tx_mined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfts.nft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfts.user')),
            ],
            options={
                'unique_together': {('nft', 'user')},
            },
        ),
    ]
