# Generated by Django 3.2.11 on 2022-02-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0011_nft_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='metadata_ipfs_uri',
            field=models.CharField(max_length=46, unique=True),
        ),
    ]
