# Generated by Django 3.2.11 on 2022-02-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0012_alter_nft_metadata_ipfs_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nfttype',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
