# Generated by Django 3.2.11 on 2022-03-01 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0013_auto_20220227_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='nft_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfts.nfttype'),
        ),
        migrations.CreateModel(
            name='NftContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content_url', models.URLField()),
                ('content_type', models.CharField(max_length=50)),
                ('nft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfts.nfttype')),
            ],
        ),
    ]
