resources:
- ./../base
- ./ingress.yaml
namePrefix: staging-
namespace: staging

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/5/value
        value: redis://staging-redis:6379/0
    target:
      kind: Deployment
      name: api-deployment
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: redis://staging-redis:6379/0
    target:
      kind: Deployment
      name: celery-worker
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: redis://staging-redis:6379/0
    target:
      kind: Deployment
      name: celery-beat
