resources:
- ./../base
namePrefix: staging-
namespace: staging-fluctua-nfts

patches:
  - patch: |-
      - op: replace
        path: /metadata/annotations
        value:
          fluxcd.io/automated: "true"
          fluxcd.io/tag.fluctua-nfts: regex:^staging.*
      - op: replace
        path: /spec/template/spec/containers/0/env/5/value
        value: redis://staging-redis:6379/0
    target:
      kind: Deployment
      name: api-deployment
  - patch: |-
      - op: replace
        path: /metadata/annotations
        value:
          fluxcd.io/automated: "true"
          fluxcd.io/tag.celery-beat: regex:^staging.*
    target:
      kind: Deployment
      name: celery-beat
  - patch: |-
      - op: replace
        path: /metadata/annotations
        value:
          fluxcd.io/automated: "true"
          fluxcd.io/tag.celery-worker: regex:^staging.*
    target:
      kind: Deployment
      name: celery-worker
