#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput

DOCKER_SHARED_DIR=/nginx
rm -rf $DOCKER_SHARED_DIR/*

cp -r staticfiles/ $DOCKER_SHARED_DIR/

exec gunicorn --config gunicorn.conf.py --pythonpath "$PWD" -b unix:$DOCKER_SHARED_DIR/gunicorn.socket -b 0.0.0.0:8888 config.wsgi:application

