apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  labels:
    app: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: denisgranha/fluctua-nft-backend:staging
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        command:
          - "/entrypoint"
        args:
          - "/start-celerybeat"
        ports:
        - containerPort: 5000
        env:
        - name: USE_DOCKER
          value: yes
        - name: IPYTHONDIR
          value: "/app/.ipython"
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings.production"
        - name: DJANGO_ADMIN_URL
          value: "admin/"
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fluctua-nfts
              key: DJANGO_SECRET_KEY
        - name: CELERY_FLOWER_USER
          valueFrom:
            secretKeyRef:
              name: fluctua-nfts
              key: CELERY_FLOWER_USER
        - name: CELERY_FLOWER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fluctua-nfts
              key: CELERY_FLOWER_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: fluctua-nfts
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: fluctua-nfts
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: fluctua-nfts
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: fluctua-nfts
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fluctua-nfts
              key: POSTGRES_PASSWORD
