apiVersion: v1
kind: Service
metadata:
  name: fluctua-nfts
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "df898558-03fa-465f-b696-5922fcf4bf81"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    service.beta.kubernetes.io/do-loadbalancer-name: "staging.apis.fluctuarecords.com"
spec:
  type: LoadBalancer
  selector:
    app: fluctua-nfts
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
