apiVersion: v1
kind: Service
metadata:
  name: fluctua-nfts
spec:
  type: ClusterIP
  selector:
    app: fluctua-nfts
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
