apiVersion: v1
kind: Service
metadata:
  name: fluctua-nfts
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "7d5a54bd-2314-4f9f-9b11-5259d3d69be4"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    service.beta.kubernetes.io/do-loadbalancer-name: "staging.apis.fluctuarecords.com"
spec:
  type: LoadBalancer
  selector:
    app: fluctua-nfts
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: 8000
