apiVersion: v1
kind: Service
metadata:
  name: fluctua-nfts
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: fluctua-nfts
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
